version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres-admin
      POSTGRES_PASSWORD: postgres-psw
      POSTGRES_DB: sql_vs_nosql_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres-admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.com
      PGADMIN_DEFAULT_PASSWORD: pg-psw
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-admin
      MONGO_INITDB_ROOT_PASSWORD: mongo-psw
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo-ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo-psw
      ME_CONFIG_BASICAUTH_USERNAME: admin-basic
      ME_CONFIG_BASICAUTH_PASSWORD: psw-basic
    depends_on:
      mongo:
        condition: service_healthy

  api-server:
    build: .
    container_name: sql-vs-nosql-api-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      APP_DATASOURCE: ${APP_DATASOURCE:-POSTGRES}
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    healthcheck:
      test: 'curl -f http://api-server:8080/actuator/health -H "Connection: close" || exit 1'
      interval: 5s
      retries: 10

  newman:
    image: postman/newman
    volumes:
      - .:/etc/newman
    depends_on:
      api-server:
        condition: service_healthy
    command: run postman/collection.json --env-var baseUrl=http://api-server:8080
    profiles: [ "test-newman" ]

volumes:
  postgres_data:
  mongo_data: