app:
  datasource: ${APP_DATASOURCE:POSTGRES}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sql_vs_nosql_postgres_db
    username: postgres-admin
    password: postgres-psw

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://mongo-admin:mongo-psw@localhost:27017/sql_vs_nosql_mongo_db?authSource=admin
      uuid-representation: standard
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health